apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deploy
  namespace: my-namespace
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-pod
          image: dailycodebuffer/dockerpublish:0.0.3
          ports:
            - containerPort: 9091
